name: TopologyAPI
description: An API Library ; Provide the functionality to access, manage and store device topologies..

# version: 1.0.0
# author: Loay Mohamed <loaymohamed1999@gmail.com>

environment:
  sdk: ">=2.12.0 <3.0.0"

dev_dependencies:
  test: ^1.17.12
